name: Create Map
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.lock -r requirements-dev.lock
      - name: Create map
        run: python main.py
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          TOM_TOM_TOKEN: ${{ secrets.TOM_TOM_TOKEN }}
          GH_USER: elgohr
      - name: Commit new map
        run: |
          git config --global user.name 'Globe Bot'
          git config --global user.email 'noreply@gohr.digital'
          git add .
          git commit -m ":arrow_up: Updated Map"
          git pull -r
          git push
